---
version: "3.9"

services:
  db:
    container_name: mysql_db
    restart: always
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: database_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  api:
    container_name: asp_api
    image: asp_api
    restart: always
    build:
      context: ../
      dockerfile: src/OAuthGitHub.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
    ports:
      - 5000:5000

  nginx:
    container_name: api_proxy
    image: nginx:1.20-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

volumes:
  mysql:
