---
version: "3.9"

services:
  db:
    container_name: oauth_db
    restart: always
    image: postgres:13.3-alpine
    volumes:
      - postgresql:/var/lib/postgresql/
    environment:
      POSTGRES_DB: oauth_github
      POSTGRES_USER: oauth_user
      POSTGRES_PASSWORD: oauth_password

  api:
    container_name: oauth_api
    image: oauth_api
    restart: always
    build:
      context: ../
      dockerfile: src/OAuthGitHub.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
    ports:
      - 5000:5000

  nginx:
    container_name: oauth_proxy
    image: nginx:1.20-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

volumes:
  postgresql:
